#!/bin/bash

cd $HOME/projects

mkdir pytest_trace_workspace

# given a python setup on os x like this: http://goo.gl/y8J4n1
virtualenv --python=/opt/local/bin/python2.7 venv

source env/bin/activate

pip install pytest

pip install pytest-bdd

# Using curl -L means follow redirect. Needed to follow goo.gl short link.
curl -L http://goo.gl/hRmoex > setup.py

# General python gitignore stuff
curl -L http://goo.gl/IIOxgs > .gitignore

# Package level gitignore for web2py stuff
curl -L http://goo.gl/TYU9gW >> .gitignore

touch LICENSE

touch README.md

# create new github repo named pytest_trace as per: http://goo.gl/aw1u3V

git init

git add .

git commit -m 'First commit'

git remote add origin https://github.com/jaymartin7/pytest_trace.git

git remote -v    # verify remote repo exists

git push origin master

mkdir tracepkg

cd tracepkg

touch main.py

touch __init__.py

mkdir dir1

touch dir1/__init__.py

mkdir dir2

touch dir2/__init__.py

mkdir dir3

touch dir3/__init__.py

mkdir test/bdd

mkdir test/unit

mkdir test/fixtures

touch test/conftest.py

# Edit setup.py with relevant settings for this directory structure

cd ..

sudo pip install -e .  # as per http://goo.gl/R0pc5s

# Edit main.py with basic Click entry point such that running 'trace' from
# bash prompt will return success string. This confirms that the tracepkg
# is importable and in pythonpath. look for: 'You called the cli function in
# main.py in tracepkg'.
trace

touch features/feature1.feature

# populate feature1 with a feature







#####################
# learning resources:
# http://developer.paylogic.com/articles/how-we-use-pytest-and-pytest-bdd-in-paylogic.html



